program: train_wab.py
project: recsys
method: bayes
metric:
  name: validation bi_ndcg@100
  goal: maximize
parameters:
  layer1:
    values: [500,600,700,800]
  layer2:
    values: [250,300,350]
  dropout:
    min: .3
    max: .5
  lr: 
    value: 0.0005
  architecture: 
    value: MULTVAE+-v3
  batch_size: 
    value: 3500
  dataset: 
    value: MAL
  epochs: 
    value: 20
  anneal_cap:
    min: .15
    max: .3
